# Disable Style/Documentation cop
Style/Documentation:
  Enabled: false

# Exclude directories and files from RuboCop
AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'

Lint/MissingSuper:
  Enabled: false
